### ISSUE TITLE
Feature to give away free accounts.

### ISSUE THREAD

**Issue by SkybuckFlying** [PascalCoinDev/PascalCoin#122]
PascalCoin needs a way to give away free accounts to new users, to expand it's user base more rapidly.

For this the following requirements must be met:

1. Accounts should be allowed to be sold at zero price.
2. Existing accounts are not allowed to buy accounts at zero price.
3. Zero-priced accounts are allowed to be transferred to new public keys (new users).

Account-holders wanting to give away accounts for free to new users should be able to do so, for this a new system must be added to pascal coin which could work as follows:

1. All accounts wanting to give away free accounts are "conceptually" pooled into a "free accounts pool".

2. A new users can request a "free account" from this "free account pool". New users can be identified based on there new public keys and new internet addresses.

3. The "free accounts pool" records the IP addresses of requests for "free accounts".

4. If an IP address is requesting "multiple accounts" within 1 hour it is forgiven but marked as "impatient" ;)

5. If an IP address keeps requesting "multiple accounts" within 24h it is marked as "hoarder" and is banned for at least a week from this "free account pool"

6. Requests of same IP five times as described above is forgiven, above this limit it is marked as hoarder and banned for a week.

7. The pool system collects all IPs and keeps these in memory or on disk if it requires too much space in memory. 

8. After 24h waiting period all requests for a free account are "honored" in the following way:

8.1 All account holders taking part in the account pool produce a random waiting time between 5 and 60 minutes or so. There random waiting time is broadcasted throughout the system. There are added into a chain. The smallest waiting time wins and is selected as the candidate to provide the free account for the new user.

8.2 The selected account holder transfers the account to the new user. 

8.3 After a new block is minted the pool checks to see if the transferred happened, the transfer may not happen if there are many pending operations, so pool should also check pending operations.

8.4 If after 10 minutes to allow this data to circulate through the network is missing the account holder is marked as "unable to provide account" and is removed from this waiting queue and possible even pool, could even be marked as untrustworthy if it happens repeatedly.

8.5 If the account was transferred to the new user verifiable by examining minted blocks/blockchain/accounts/banks then the transferred is considered successfull and the IP can be removed out of the system.

Now ofcourse the IP could try again, however would need to do so with a different client/pc,
Period could also be extended to a week.

Hashing of IPs could also be done to offer a little bit of privacy protection.

A hash which scales down 32 bits to 16 bits or maybe 8 bits or 4 bits or even 1 bit could be tried.

1 bit is perhaps a bit too low, since there could be multiple new users at any given time.

Perhaps 4 or 8 bits would suffice. There is some chance of a hash collision which could be solved by adding some block number or so for which the transfer is to take place.

For example
special_hash( ip + blocknumber)

Not sure if this is "race proof", I may alter this text later on, right now I have to go.

Maybe more on this later, bye for now.

You may also expand this into a pip. Or I could try and put it into a pip later on. May try a beta implementation if I get some seriously interested feedback on this.

**Comment by HermanSchoenfeld** [comment]
Why don’t you join the Discord and discuss there, no need for github spam.

You can’t give away accounts for free because of Tragedy of the Commons problem. Accounts will shortly be availble in a variety of ways, but at a $1 price minimum will be required.

**Comment by SkybuckFlying** [comment]
This idea is to defeat (somewhat) "tragedy of the commons" by reducing their incentive to do so.
(Can't join discord anymore, was banned there =D, like this/forums and such better anyway =D)

It has to be free, $1 would create a deadlock in a way. Have to earn "money" to buy account, but don't have account to earn money, so can't earn money so can't buy account :). Now let's suppose there is only pascal coin money, then houston we have a problem !

There is an incentive to account holders to give them away for free, so there should be something build into pascalcoin to allow them to do that, they can take the risk of the "tragedy of the commons", the system could thus help to reduce some of that risk.

**Comment by HermanSchoenfeld** [comment]
You’ve been unbanned from Discord, we prefer you flood there instead of GitHub. Thanks.
