### ISSUE TITLE
official miner does not start on CUDA/Nvidia

### ISSUE THREAD

**Issue by kruisdraad** [PascalCoinDev/PascalCoin#13]
It does not report any errors, just a input server name message and then just hangs. Using CPU it will work fine

passing -s option returns a access violation on 00000010004492C

**Comment by PascalCoinDev** [comment]
Open source miner is only OpenCL, not for CUDA.
I've not tested on NVIDIA cards, I don't know if NVIDIA cards suports OpenCL drivers... sorry.

Someone running NVIDIA cards with OpenCL miner successfully?

**Comment by kruisdraad** [comment]
i've been mining with OpenCL on different platforms (e.g. zcash, ethereum, etc) without issues ... not using cuda but opencl will loose a little in performance but should work. The cards are detected but when starting it just hangs.

**Comment by RedTailedMink** [comment]
i have the same issue. nvidia does include opencl drivers.
the total error is
Exception at 000000010004492C: EAccessViolation:
                                                Access violation.

**Comment by bathrobehero** [comment]
Same issue.

**Comment by PascalCoinDev** [comment]
Sorry... I can't test it on NVIDIA to help you...

**Comment by kruisdraad** [comment]
@PascalCoin so you need a NVidia rig to test it on? i can arrange that

**Comment by RedTailedMink** [comment]
The unofficial cuda miner is working i just tested it. you have to start the .jar file then start one of the .exe's. use the benchmarks to determine which one you should use.

**Comment by kruisdraad** [comment]
'THE' unofficial minder ... which one, etc etc etc

i've tried the one i think you mean, however it latst last error: no error and then stops
