### ISSUE TITLE
Delphi XE3 build failed [Pascaloin Wallet GUI-Classic]

### ISSUE THREAD

**Issue by CFTechno** [PascalCoinDev/PascalCoin#136]
Trying to build the GUI-Classic in Delphi XE3 fails because of the "Decimalseparator" and "ThousandSeparator"  in UAccounts.pas

Changed to "formatsettings.ThousandSeparator" and "formatsettings.Decimalseparator" solved the problem.

**Comment by Xor-el** [comment]
@CFTechno ,
Thanks for the report.
 currently the codebase is being managed with Delphi 2010 and Lazarus.
Whether the codebase will be moved fully to Lazarus or Improved to compile both on Modern Delphi and Lazarus is Undecided at the moment.

**Comment by SkybuckFlying** [comment]
This issue is fixed in this commit (scroll way down to skip over DFM changes and see the code fix):

https://github.com/SkybuckFlying/PascalCoin/commit/90b91f3adffeb5d58404d4dd7b62471075b118e0

Doesn't get any more exact then that ! ;)

Check the Delphi docs ! ;)
