### ISSUE TITLE
Delphi XE3 build failed [Pascaloin Wallet & RandomHash_Tests]

### ISSUE THREAD

**Issue by CFTechno** [PascalCoinDev/PascalCoin#137]
Building both PascalCoin and RandomHash.tests using Delphi XE3 failed because of

  {$mode delphi} in several unit

changing that into 

{$ifdef fpc}
  {$mode delphi}
{$endif}

Solved that problem.

However the error "Type 'TAutoPtr<T>' is not completely defined" on the code
`
  TAutoPtr<T> = record
    private type
      __TAutoPtr_T = TAutoPtr<T>;` in unit UMemory I could not solve.

**Comment by Xor-el** [comment]
@CFTechno , same reply as [this](https://github.com/PascalCoin/PascalCoin/issues/136).

**Comment by CFTechno** [comment]
I just tested it with D2010 and it fails with the same error message.

**Comment by Xor-el** [comment]
UMemory.pas has not been tested with Delphi so it will probably not compile.
Our current build environment is Lazarus/FPC.
May be in the future, compilation might be supported for Delphi.

**Comment by CFTechno** [comment]
ok, will install Lazarus/FPC then..
