### ISSUE TITLE
Source code of installer is missing...

### ISSUE THREAD

**Issue by DelphiniumCoin** [PascalCoinDev/PascalCoin#154]
This project is incomplete.

The source code of the installer is missing.

I suspect the installer adds a firewall rule to windows firewall, otherwise this application/project won't work on many windows installations.

**Comment by DelphiniumCoin** [comment]
I tried to proof this by removing PascalCoin in a virtual machine where it was already installed via installer, by uninstalling it, removing the firewall rule, and then re-installing via installer.

As far as I can tell no firewall rule was automatically added. (The VM doesn't have an internet connection though but windows 10 firewall is running)

After a while after PascalCoin is started the windows firewall will eventually access if to allow access to this application. It might not allows ask this though on some systems. Not sure why, perhaps some windows systems are "locked down" where these questions are not asked to users, but simply denied by default.

**Comment by DelphiniumCoin** [comment]
Not sure what happens if a User chooses cancel... doesn't seem like this question pops up again. This may cause pascalcoin to stop working on such systems.

Strangely enough even if cancel was choosen, a firewall rule was added to the windows firewall allow pascalcoin to work on public networks, so for now it seems like pascalcoin will work even if cancel was chosen.

**Comment by DelphiniumCoin** [comment]
PascalCoin seems to use InnoSetup which is already open source and is on github. One possible solution to solve this issue is to include the InnoSetup script file *.iss with the PascalCoin project source code.

**Comment by PascalCoinDev** [comment]
If user does not agree with released binary/installer can use the source code to compile. The installer source does not sense
