### ISSUE TITLE
Assigning IP address in Ubuntu

### ISSUE THREAD

**Issue by stealthmachines** [PascalCoinDev/PascalCoin#16]
I'm trying to figure out how to point an Ubuntu based miner to my windows-based wallet.  I tried the command ./pascalcoin_daemon -r -s 192.168.0.103:4009 -p 0 -d 0,1,2,3,4,5 -n stealth5 but it didn't work

1) Even though I have a wallet on another client which I want my farm to point to, I can't seem to figure out the correct command to use in Ubuntu?
2)  Do I need to install a wallet in Ubuntu even though another client already handles the wallet?
3) With version 1.4.2 do I need to install any other dependencies which are not provided with the latest tar ball?

./pascalcoin_daemon -r -0 192.168.0.110:4009 -p 0 -d 0,1,2,3,4,5 -n stealth5

26-01-2017 17:44:39.738 Starting PascalCoin server
26-01-2017 17:44:39.739 TID:22FB1700 [Info] <TPCDaemon> Daemon Start -1
26-01-2017 17:44:39.739 TID:22BB0700 [Info] <TPCDaemonThread> START PascalCoin Server
26-01-2017 17:44:39.739 TID:22FB1700 [Info] <TPCDaemon> Daemon execute: 0
26-01-2017 17:44:39.741 TID:22BB0700 [Info] <TNode> TNode.Create
26-01-2017 17:44:39.741 TID:22BB0700 [Info] <TNetServer> Closing server
26-01-2017 17:44:39.741 TID:22BB0700 [Info] <TRPCServerThread> Activating RPC-JSON Server on port 4003
26-01-2017 17:44:39.741 TID:22BB0700 [Info] <TPCDaemonThread> RPC server is active on port 4003
26-01-2017 17:44:39.741 TID:22BB0700 [Info] <TPCDaemonThread> Activating RPC logs on file /home/owner/PascalCoin/pascalcoin_rpc.log
26-01-2017 17:44:39.743 TID:22BB0700 [Info] <TFileStorage> Loading SafeBox with 56500 blocks from file /home/owner/PascalCoin/Data/bank3.bank
26-01-2017 17:44:47.173 TID:22BB0700 [Info] <TPCBank> Start restoring from disk operations (Max 4294967295) BlockCount: 56500 Orphan: 
26-01-2017 17:44:55.845 TID:22BB0700 [Info] <TPCBank> End restoring from disk operations (Max 4294967295) Orphan:  Restored 56805 blocks
26-01-2017 17:44:55.922 TID:22BB0700 [Info] <TNetData> TNetData.Create
26-01-2017 17:44:55.923 TID:191DC700 [Info] <TThreadDiscoverConnection> Starting discovery of connection bpascal1.dynamic-dns.net:4004
26-01-2017 17:44:55.923 TID:189DA700 [Info] <TThreadDiscoverConnection> Starting discovery of connection bpascal2.dynamic-dns.net:4004
26-01-2017 17:44:55.923 TID:22BB0700 [Info] <TNetServer> Activating server on port 4004
26-01-2017 17:44:55.923 TID:18DDB700 [Info] <TThreadDiscoverConnection> Starting discovery of connection pascalcoin1.dns1.us:4004
26-01-2017 17:44:55.923 TID:185D9700 [Info] <TThreadDiscoverConnection> Starting discovery of connection pascalcoin2.ddns.net:4004
26-01-2017 17:44:55.924 TID:22BB0700 [Info] <TPCDaemonThread> Generated new miner name: 2017-01-26 17:44
26-01-2017 17:44:55.924 TID:22BB0700 [Info] <TPCDaemonThread> Activating RPC Miner Server on port 4009, name "2017-01-26 17:44", max conections 1000 and public key 3Ghhbovh8CEkBEqJNHbGD5UqSEpgRVmijJL94vuHZs41xeVdcLFDYs84xqM7bHwAWfVA8bsj1rFjGSCoyaUk16ubFgAQPH6sXw8Kds
26-01-2017 17:44:55.925 TID:1287F700 [Info] <TThreadDiscoverConnection> Starting discovery of connection pascalcoin1.dynamic-dns.net:4004
26-01-2017 17:44:56.131 TID:191DC700 [Info] <TNetClient> Connected to a server 80.24.12.98:4004

Thanks!

**Comment by PascalCoinDev** [comment]
You're running PascalCoin core (pascalcoin_deamon) and you're sending information like if core was a miner... For now, there is no miner (made by dev) for linux. Perhaps in a future...
