### ISSUE TITLE
nodestatus

### ISSUE THREAD

**Issue by ek1977** [PascalCoinDev/PascalCoin#167]
The PascalCoin issue tracker on github.com is **ONLY** used for reporting bugs. No feature requests accepted here, please visit our discord to bring in new ideas: https://discord.gg/sJqcgtD

Node is syncing but not yet fully synced.  Trying to get a node status but the nodestatus method returns an error code.  other RPC calls are working as expected.

## Operation System & Version
Ubuntu Latest, running PascalCoinWallet_MAINNET_4.0.2d_Linux.tar.gz binary from the releases page.

## Expected Behavior
method nodestatus should output nodestatus details as shown in the documentation.

## Current Behavior
nodestatus method returns following:
{'error': {'code': 1021, 'message': ''}, 'id': 123, 'jsonrpc': '2.0'}

**Comment by PascalCoinDev** [comment]
This is because config ini file is open to all ip's, and in order to protect from attack, this call is limited to only a whitelists IP.
Put a whitelist and will allow to obtain nodestatus call
