### ISSUE TITLE
Application.CreateForm called twice, probably some latest Delphi bug.

### ISSUE THREAD

**Issue by SkybuckFlying** [PascalCoinDev/PascalCoin#168]
Latest update introduced a bug:

begin
  Application.Initialize;
  {$IFDEF WINDOWS}Application.MainFormOnTaskbar := True;{$ENDIF}
  Application.Title := 'Pascal Coin Wallet, Miner & Explorer';
  Application.CreateForm(TFRMWallet, FRMWallet);
  Application.CreateForm(TFRMWallet, FRMWallet);
  Application.Run;
end.

Notice how CreateForm is called twice ?!

I have seen this bug in other projects, it's probably some weird bug caused by latest Delphi.

**Comment by Xor-el** [comment]
@SkybuckFlying , thanks for reporting it.
it is a bug with the Delphi IDE.
meanwhile, it has been corrected via commit https://github.com/PascalCoin/PascalCoin/commit/674ba28a5030ccffba89da0723ab062340e285d3
