### ISSUE TITLE
Parameters swapped ?

### ISSUE THREAD

**Issue by SkybuckFlying** [PascalCoinDev/PascalCoin#169]
commit f7bf240a97df1a15357bb44e4d79e8c704c088b1 has the parameters for the move function/routine swapped ?!

Is PascalCoin sure that this is correct ?!?

Odd...

CopyMemory(@FReceivedBuffer[lasti],ms.Memory,ms.Size);
move(ms.Memory^,FReceivedBuffer[lasti],ms.Size);

Ok now I see what is going on here two different functions... hmmm bit scary :)

**Comment by Xor-el** [comment]
@SkybuckFlying ,
See the definition of CopyMemory in Windows.pas, the orders are reserved.
CopyMemory follows the C memmove convention while Move in Pascal follows the logical convention.

`procedure CopyMemory(Destination: Pointer; Source: Pointer; Length: DWORD);
begin
  Move(Source^, Destination^, Length);
end;`

**Comment by SkybuckFlying** [comment]
Hmmm, is there a linux version too ? :) How cross-platform is this ? :)

Also why was move replaced with CopyMemory ?

(I have seen move routine causes crashes during debugging though, but not sure why ;))

**Comment by Xor-el** [comment]
> Hmmm, is there a linux version too ? :) How cross-platform is this ? :)
> 
> Also why was move replaced with CopyMemory ?
> 
> (I have seen move routine causes crashes during debugging though, but not sure why ;))

1. It's fully crossplatform
2. See commit details
3. That might be due to range issues.

**Comment by SkybuckFlying** [comment]
Oh now I see,  CopyMemory was actually replaced with move and not vice-versa :) thx ! ;) :)
