### ISSUE TITLE
Is there an API to know which accounts were created by a block?

### ISSUE THREAD

**Issue by fairglu** [PascalCoinDev/PascalCoin#17]
Right now the number created by block is fixed to 5 if I understood correctly, so block 0 created account 0-4, block 1 created 5-9, etc. (correct me if I am wrong).

But is that number subject to future revisions? If so would an API returning the first & last account created by a block be appropriate?

Finally, if that API could also list the account(s) that received the block reward, that could also be more future-proof.

**Comment by PascalCoinDev** [comment]
Accounts will be 5 per block, no plans for change it, no need to add this API method.

**Comment by fairglu** [comment]
Could you reconsider? I am also thinking of possible clones/altcoins of Pascalcoin, for which the number of created accounts per block would be one of the parameters that could be adjusted by the alt (or even made dynamic).
Having a standard API for that would ease the pain of supporting these alts.
