### ISSUE TITLE
[RandomHash] GPU and ASIC Resistance

### ISSUE THREAD

**Issue by ClashLuke** [PascalCoinDev/PascalCoin#171]
I might be wrong, but after some analysis of your algorithm, I came across the following points.

First of all, you don't have to store all your "paths" of nonces, so essentially it's enough to just save the last 16 nonces in the L1 cache with the hashes corresponding to them.
If there is enough L2 memory you might aswell save the fully assembled blocks in the L2 cache, but that's not necessary and changes the speed only a slight bit.

Back to the L1 cache.
If we now assume that we only save one path at any given time, we can optimise the memory utilisation a lot. We now have up to 28x256bit (7KiB) in the L1 cache, instead of 8KiB\*thread count.
What exactly does that give us?
Scalability. We can now add as many processing cores as we want since we only need another 4x256bit (1KiB) per thread.
*Less useless math, more arguments please*
If we now take a [Vega 64](https://www.techpowerup.com/gpu-specs/radeon-rx-vega-64.c2871), we have 4096 stream processors and grouped into 64 compute units (CU) of 64 processors, with 16KiB L1 cache and 4MB L2 cache.

In other words, the whole Merkle tree can be kept in the L1 cache while the L2 cache stores the current values.

For an ASIC, one could strip out everything of a GPU that's not needed in hashing, shrink both caches and therefore have highly increased efficiency compared to GPUs, which already run 4096 instances at once 

To conclude, I would say that with GPUs you would have an additional speed boost of about x256, while still keeping the speed boost of the hash function you're using. Resulting in about x1024 to x2048 on GPU, even higher results on ASIC.

Again, I want to add that I'm probably missing some points of RandomHash, but from what I've observed, the thing you changed, what made your hash unique, does not need your own requirements.

I'd love to see some discussion below this post, thanks for reading.

**Comment by HermanSchoenfeld** [comment]
Hi Luke,

Thanks for looking at RandomHash, encourage you to investigate more.  To address your points,

(1) Every round has a dependency on the transitive closure of the outputs all prior and neighboring rounds. It follows that in order to calculate any round you need to have calculated all prior and neighboring rounds and **their outputs must be known in memory**. So, in this sense, the "path to all nonces" is strictly required. In fact, this dependency is amplified (in terms of resource utilization) via memory-expansion of dependent round outputs.

(2) Since rest of your arguments are predicated on NOT (1), they do not follow.

I will be providing a C# implementation soon in NPascalCoin which will be easier to understand.

Thanks.

**Comment by ClashLuke** [comment]
But I did assume that aswell. I simply store all the previous data once, instead of n times.
So that you have one precalculation and afterwords either not propagate and leave it at the same history (saved are n1..n32, not n2..n33 and their respective outputs) or change it by taking one core CU which sets the current "path".

I'm sure the issue can be summarised as "miners are not forced but advised to save every nonce history". The results of this assumption can be seen above.

**Comment by HermanSchoenfeld** [comment]
They don't need history of every nonce, only the last nonce calculated to round N-1. The next nonce is always the last "most calculated" nonce, which is always calculated to 50%. Other less partially calculated nonces are ignored, since there is always one at 50%.

**Comment by ClashLuke** [comment]
To be fair, you already have much more calculated than 50%. And that's what I'm talking about. You simply keep those nonces and their corresponding hashes in the memory, instead of propagating.
