### ISSUE TITLE
findaccounts with 'name' and 'exact:false' not working as expected

### ISSUE THREAD

**Issue by bbedward** [PascalCoinDev/PascalCoin#190]
##  Operation System & Version
Ubuntu 18.04
PascalCoin 4.1

## Expected Behavior
Expect that RPC `findaccounts` with a `name` and `exact:false` specified in parameters to return accounts where the name contains the value.

## Current Behavior
Every account is returned, even ones with empty names.

For example:
`{"jsonrpc":"2.0","method":"findaccounts","params":{"name":"ykt", "exact":false},"id":123}`

returns an array with every account on the network starting at 0

```
        {
            "account": 0,
            "enc_pubkey": "CA0220006E75266E1865288874BFE1C3A9686BCF4D22CADCC250B134EA2C470A9E3F912B2000F8362CB5EE97113D93880303E99B63208CEBDB62D49874D739E33DFFFD3C4162",
            "balance": 441.8484,
            "n_operation": 4,
            "updated_b": 340110,
            "state": "normal",
            "name": "pascalcoin-dev",
            "type": 1000
        },
        {
            "account": 1,
            "enc_pubkey": "CA0220001FD6019F7FBFCD9A34491643287402FB0CCB77F2A4F99482ADC11137CDF1FBD6200046924461A9069850A64E48E8EDB9C88764D3A0DC74AF929E335719F8A65B809B",
            "balance": 0.101,
            "n_operation": 2,
            "updated_b": 300425,
            "state": "normal",
            "name": "",
            "type": 0
        },
        {
            "account": 2,
            "enc_pubkey": "CA0220001FD6019F7FBFCD9A34491643287402FB0CCB77F2A4F99482ADC11137CDF1FBD6200046924461A9069850A64E48E8EDB9C88764D3A0DC74AF929E335719F8A65B809B",
            "balance": 0.001,
            "n_operation": 3,
            "updated_b": 200004,
            "state": "normal",
            "name": "",
            "type": 0
        },
```

## Possible Solution
Fix the `findaccounts` RPC to correctly do partial name searches

## Steps to Reproduce
1. Execute the findaccounts RPC such as: `curl -g -d '{"jsonrpc":"2.0","method":"findaccounts","params":{"name":"ykt", "exact":false},"id":123}' localhost:4003`

## Context (Environment)
Attempting to implement an account name search, based on a partial match of the name. This is a feature we want to include in the Blaise wallet

**Comment by PascalCoinDev** [comment]
Fixed on PascalCoin github. Thanks
