### ISSUE TITLE
OPHASH question

### ISSUE THREAD

**Issue by fairglu** [PascalCoinDev/PascalCoin#20]
When looking at OPHASH values, part of the OPHASH listed in the RPC API (and in the explorer) looks like a double hexadecimal encoding, f.i. in http://explorer.pascalcoin.org/blockoperation.php?block=58499 the three op hashes are

83E40000BE5B04000F3800004242464336314530303533343639433431363135
83E40000BE5B0400103800003637303045334246463739373037423641333243
83E40000BE5B0400113800004233443938373441394534304430454437444443

note how the start of the hash "83E40000BE5B04000F380000" is a hex of a binary value, while the end of the hash after that is always (?) an hexadecimal representation of an upper-case hexadecimal string.

Is that a bug of the RPC API or did I miss something interesting about the way OPHASHes are constructed ?

Thanks!

**Comment by PascalCoinDev** [comment]
Ophash has 4 parts. First part (block) can be "00000000" (no block, this is the value when operation has been executed prior to be added to the blockchain, equals to a pending operation) or block number in little endian. (Both representations are correct)

See source code:

File UBlockChain.pas
Line 2074
class function TPCOperation.OperationHash(op: TPCOperation; Block : Cardinal): TRawBytes;
  { OperationHash is a 32 bytes value.
    First 4 bytes (0..3) are Block in little endian
    Next 4 bytes (4..7) are Account in little endian
    Next 4 bytes (8..11) are N_Operation in little endian
    Next 20 bytes (12..31) are a RipeMD160 of the operation buffer to hash
    //
    This format is easy to undecode because include account and n_operation
   }

**Comment by fairglu** [comment]
Thanks!

Would it be possible to avoid the double hex encoding for the RIPEMD portion?
For instance rather than using '4233443938373441394534304430454437444443' the OPHASH could use the RIPEMD directly as 'B3D9874A9E40D0ED7DDC'.

This shortens the OPHASH a bit and increase its readibility, as the RIPEMD part of the hash is currently buried among '3' & '4' digits because of the double-hex enconding, so for instance instead of '83E40000BE5B0400113800004233443938373441394534304430454437444443' the OPHASH would be just '83E40000BE5B040011380000B3D9874A9E40D0ED7DDC'

Also finally, what about reversing the order and placing the RIPEMD in front, ie 'B3D9874A9E40D0ED7DDC83E40000BE5B040011380000' ?
The point there is that the most variable part of the OPHASH is the RIPEMD, and so when reading an OPHASH, the "most variable" part would be in front, which allows human to tell OPHASHes apart more easily.

I am asking all this in the context of an alternative explorer (for cryptoID.info, which FWIW is also written in Pascal), the current OPHASH are a bit long to display, and when truncated for display on mobile devices, current OPHASH lose their most variable portion and all look the same, f.i. the three OPHASH I listed can appear as 

83E40000BE5B0400...
83E40000BE5B0400...
83E40000BE5B0400...

with the proposed changes they would appear as

BBFC61E0053469C...
6700E3BFF79707B...
B3D9874A9E40D0...

The technical hash data is unchanged, but the human-visible hash data makes it obvious the ops are different.
That format would also be easier to autocomplete for searches and such when someone is looking up an OPHASH (f.i. to lookup the status of a pending operation).

Thanks for your consideration!

**Comment by PascalCoinDev** [comment]
I understand. It can be changed, of course, but third party devs are developing solutions with current ophash format (exchanges... miners...) so it's not a good idea to change now...
