### ISSUE TITLE
Fork PascalCoin

### ISSUE THREAD

**Issue by dinarpay** [PascalCoinDev/PascalCoin#205]
Hello
I want to build a stable cryptocurrency in my country and the price is the same as the local currency
It's not for trading, I want it to transfer money, and pay merchants
Immediately, without fees, and the most important thing is high security

The other part of the question
Does this wallet work with your coin code and is fully compatible with it?
https://github.com/appditto/blaise_wallet_flutter
Because as far as I know it only works with the nano cryptocurrency code

Thanks

**Comment by PascalCoinDev** [comment]
Blaise wallet is for PascalCoin
