### ISSUE TITLE
How to build pascalcoinminer?

### ISSUE THREAD

**Issue by dzamosenchuk** [PascalCoinDev/PascalCoin#21]
Hello!
I have next situation: I want mine pascal coins. But I have computers with good CPU and worse GPU. They work under Ubuntu OS. And I can’t understand how to build pascalcoinminer from sources and configure to work with pool (for example nanopool.org). Please give me a link or tutorial how to do this.

**Comment by PascalCoinDev** [comment]
Please follow Wiki instructions:
https://github.com/PascalCoin/PascalCoin/wiki/Compile-instructions
