### ISSUE TITLE
OSX - MacOS building

### ISSUE THREAD

**Issue by theghost1980** [PascalCoinDev/PascalCoin#22]
Hello guys. What do i need to make possible the building option under MacOS? i'm using MacOs Sierra 10.12.3.

I could work on it, but I need some guidelines to start.
Thanks for your time!

**Comment by PascalCoinDev** [comment]
Follow instructions on Wiki https://github.com/PascalCoin/PascalCoin/wiki/Compile-instructions

It should be similar than Linux building... using Lazarus GUI compiler, but I've no MAC and I can't test it.

Please, if you finally build it send me instructions and I'll modify Wiki instructions.

Thanks

**Comment by theghost1980** [comment]
Hi there thanks for answer. So far I’m getting an error by using Lazarus when compiling, I guess it’s the method of some params:




i will keep trying anyway and I will let you to know.


Thanks for your time!

**Comment by ebaizel** [comment]
any luck with this @theghost1980?

**Comment by SkybuckFlying** [comment]
Delphi XE 10.1 Seatle has Mac Os X support. I have this development environment installed. It would require me to remotely connect to your Max OsX and your computer would have to run something called PAServer. (Platform Assistent), that way PascalCoin can be cross-compiled/build and tested on your machine. This cannot be done on Windows currently, so building for Max OsX requires a two computer setup. We could join/connect our computers together over the internet and work together to make this happen.

The exact details are on embarcaderos website/help:

http://docwiki.embarcadero.com/RADStudio/Tokyo/en/Installing_the_Platform_Assistant_on_a_Mac

This assistant can be freely downloaded from there, try installing it on your Mac OSX and report back findings/results ! :)

If you interested in trying this out contact me at skybuck2000@hotmail.com
