### ISSUE TITLE
RPC findoperation fails to find operation by opHash 

### ISSUE THREAD

**Issue by ghost** [PascalCoinDev/PascalCoin#23]
Hi

Here is scenario:

1. User calls RPC sendto and stores opHash received as result of this call
opHash = 0000000005000000020000003837413134323336363533384244454641454232

2. Operation in included in the next mined block and now has opHash = 4810000005000000020000003837413134323336363533384244454641454232

3.  Later user wants to check if that transaction exists in blockchain, so he calls RPC findoperation with argument opHash:0000000005000000020000003837413134323336363533384244454641454232

4. Node cannot find operation, replays with error: "Value is not a valid OpHash". 

I understand that opHash changes,  but still Node should be able to find that transaction by its original opHash.  There is even  aspecial part of code for that purporse in function TNode.FindOperation ( after line     // block=0 and not found... start searching at block updated by account updated_block  )

**Comment by PascalCoinDev** [comment]
4. If node cannot find operation, that means that this operation does not exists.
Perhaps you have made this operation on an orphan blockchain?

**Comment by ghost** [comment]
I was working on testnet ( version 1.5.0 ) with only one node. Mining , sending and receiving operations were performed on the same node.

**Comment by PascalCoinDev** [comment]
Fixed.
https://github.com/PascalCoin/PascalCoin/commit/eeee928201a06b46cca6dfb8f1efdb4d904aa3d8

Thanks xiphon user for find the bug and the solution
