### ISSUE TITLE
Arch linux x86_64 libcrypto.so.1.0.0 SIGSEGV on startup

### ISSUE THREAD

**Issue by tomasbrod** [PascalCoinDev/PascalCoin#24]
Compiled with lazarus 1.6.2 fpc  3.0.2. I changed the define in config.inc to use Synapse_OpenSSLv10. But it crashes <ins>with SIGSEGV at 4239D0</ins> on startup. I guess it is due to the strange OpenSSL inport. See how I import OpenSSL in my (experimental) project:  https://github.com/tomasbrod/net/blob/dev/crypto.pas

**Comment by md2prof** [comment]
I can confirm that openssl 1.1.0e works fine.  See aur.archlinux.org/packages/pascalcoin
