### ISSUE TITLE
Size mismatch in class function TNetData.ExtractHeaderInfo in UNetProtocol.pas

### ISSUE THREAD

**Issue by SkybuckFlying** [PascalCoinDev/PascalCoin#254]
In:

class function TNetData.ExtractHeaderInfo(buffer : TExtendedStream; var HeaderData : TNetHeaderData; DataBuffer : TExtendedStream; var IsValidHeaderButNeedMoreData : Boolean) : Boolean;

Following line has a size mismatch:

		buffer.Read( HeaderData.error_code, 2); 

In reality error_code is integer which is size 4 !

Not reading all 4 bytes could potentially cause garbage in (higher bytes?) of this error code.

**Comment by PascalCoinDev** [comment]
` HeaderData.error_code` type is 4 bytes lenght, but is initialized to 0 so reading only 2 bytes does not produce a bug

But, totally agree with you that better is to change ` HeaderData.error_code` type to Word or similar
