### ISSUE TITLE
Sloppy code in procedure TNetConnection.DoProcess_GetPendingOperations; in UNetProtocol.pas

### ISSUE THREAD

**Issue by SkybuckFlying** [PascalCoinDev/PascalCoin#255]
In routine:

procedure TNetConnection.DoProcess_GetPendingOperations;

In file:

UNetProtocol.pas

Following line is sloppy code:	

If (dataReceived.Read( cTotalByOther,SizeOf(cTotal))<SizeOf(cTotal)) then begin

This should be:

If (dataReceived.Read( cTotalByOther,SizeOf(cTotalByOther))<SizeOf(cTotalByOther)) then begin

**Comment by PascalCoinDev** [comment]
Agree but due `cTotalByOther` and `cTotal` are same type there is no change. Push a pull request. please

**Comment by SkybuckFlying** [comment]
Please assign this to me so I can fix it ! =D
