### ISSUE TITLE
Can't compile PascalCoinMiner under Linux

### ISSUE THREAD

**Issue by natugle** [PascalCoinDev/PascalCoin#29]
When I try to compile PascalCoinMiner with Lazarus 1.6.4 and FPC 3.0.2 under Linux Mint 18.1 I get al ot of warnings and hint :)

But I also get 5 errors
DelphiCL.pas(2198,37) Error: Incompatible types: got "Pointer" expected "LongWord"
DelphiCL.pas(2200,17) Error: Identifier not found "glXGetCurrentDisplay"
DelphiCL.pas(2575,3) Error: Identifier not found "ZeroMemory"
DelphiCL.pas(2614,3) Error: Identifier not found "ZeroMemory"

Perhaps FillChar (orig,SizeOf(orig),0); will do the same.
I guess it is Delphi stuff not implementet in Lazarus/FPC

PascalCoinMiner.pp(159,7) Error: Identifier not found "GotoXY32"
It stops complaining when I change to "GotoXY", But I'm not sure it is enough :)

**Comment by PascalCoinDev** [comment]
Yes. Current source code is only valid for Windows OS, not tested/modified for Linux. 
There is no plan to allow this.
Meanwhile you can use wolf sgminer for PascalCoin, with native PascalCoin protocol support.
