### ISSUE TITLE
1.5.4 api getaccount

### ISSUE THREAD

**Issue by ghost** [PascalCoinDev/PascalCoin#30]
In 1.5.3, calling getaccount returns correct data. In 1.5.4, the same call returns "Account not found"

**Comment by PascalCoinDev** [comment]
I have not found an error testing on 1.5.4.
I provide a CURL example:
curl -X POST --data '{"jsonrpc":"2.0","method":"getaccount","params":{"account":20000},"id":123}' http://localhost:4003

Result:
{"result":{"account":20000,"enc_pubkey":"CA02200080B8A4EBDF2420D4843B9C776EFDF25BD84F1D978E6BB6698ED920852F4BD57E200008823095DF8D1F9BFE411E2FE36CB3676907D881EB436F79BDD9CA132B3EB313","balance":0,"n_operation":1,"updated_b":7657},"id":123,"jsonrpc":"2.0"}

I close this issue, If you can provide an example of error, reopen it and provide CURL call
