### ISSUE TITLE
Feature: Display Coin Value

### ISSUE THREAD

**Issue by ghost** [PascalCoinDev/PascalCoin#32]
I keep my coin at an exchange because I like to see what they are worth. Could something be integrated into the wallet to get the current price from Polo, and then display to the user what the value would be in BTC and USD?

**Comment by SkybuckFlying** [comment]
This is an interesting feature and definetly possible... but this would "tie" PascalCoin to a certain "data provider"...

Perhaps PascalCoin could create a plug-in system for this and then calculate average price from all data provided from plug-ins.

This way at least it would not be "tied" to a certain provider. But user can decide themselfes which ones to "tie" to dependent on which plugins they installed for this !
