### ISSUE TITLE
Multiaccounts change key error

### ISSUE THREAD

**Issue by venticello** [PascalCoinDev/PascalCoin#38]
![image](https://user-images.githubusercontent.com/1232990/28037167-34573c44-65c3-11e7-943d-b37f1c599ea0.png)
version 2.0.0 windows 10

**Comment by ghost** [comment]
I believe this is by design. To prevent spamming in V2, a fee must be included with multi-account operations. If you include a .0001 fee, this message should not occur.

**Comment by venticello** [comment]
Display error should be more understandable for ordinary users.
