### ISSUE TITLE
What is the maximum number of PascalCoins that can exist?

### ISSUE THREAD

**Issue by 253153** [PascalCoinDev/PascalCoin#41]
I read on the CoinMarketCap website that there are 11,826,400 PascalCoins out right now, what is the maximum amount of PascalCoins that can exist? Or is there no cap?

**Comment by ghost** [comment]
Come join the slack, real time chat with PASC community. Also, at the coin website, there is a diagram that answers your question. http://www.pascalcoin.org/slack-self-invite/

**Comment by 253153** [comment]
@jmknapp80  Thanks, will do. Meanwhile, do you have an answer here?

**Comment by PascalCoinDev** [comment]
Each 420480 blocks (aprox 4 years) miners reward will decrease at half: Starting with 100,50,25,... and the minimum is 1, that will be forever 1 pasc per block
See: http://i.imgur.com/pWqYzVd.png
