### ISSUE TITLE
PIP-0001 Discussion

### ISSUE THREAD

**Issue by HermanSchoenfeld** [PascalCoinDev/PascalCoin#44]
Please provide your comments regarding [PIP-0001](https://github.com/PascalCoin/PascalCoin/blob/master/PIP/PIP-0001.md) here.

**Comment by SkybuckFlying** [comment]
Software should be tested first.  (Tested seperatedly and especially fully integrated into PascalCoin and perhaps testnet ?!) before being applied to "main net/production net/pascal coin".

What is the purpose of PIP without software testing/acceptance phase ? Design decisions ?

If a PIP according to current PIP-0001 is accepted ? How will it be implemented ? Would there be a test phase ?

Are proposals supposed to be pre-tested ?

This is very fuzzy and needs further explanation ?!?
