### ISSUE TITLE
How to mine on Linux?

### ISSUE THREAD

**Issue by tsr8** [PascalCoinDev/PascalCoin#46]
How to compile and use PascalCoinMiner on Linux system?

**Comment by HermanSchoenfeld** [comment]
Hi Tomasz,

Please join our slack and ask your question on #mining, plenty of members will help.

pascalcoin.org/slack-self-invite/ <http://pascalcoin.org/slack-self-invite/>


Regards,
Herman Schoenfeld	M  +61 437 553 144
AU	T  +61 7 3195 3224	F  +61 7 3188 6009
US	T  +1 (562) 661 8263	F  +1 (562) 661 8263



 <http://www.sphere10.com/>
 <http://www.sphere10.com/>
