### ISSUE TITLE
Minning pascalcoin impossible with pascalcoinmine

### ISSUE THREAD

**Issue by Stefvw26** [PascalCoinDev/PascalCoin#54]
At first I created several workers on coinotron, but only one minne, no more worker is working now, I tried several mining applications and it is the same result.

And I have an error message in the console to pascalcoinminer :  "Error Received bad values for target and target_pow!" 

I can leave more than 5 hours the balance does not move at all :-(

help me please

**Comment by P3t3rT1j** [comment]
i got the same erro, could anyone help us?
