### ISSUE TITLE
Customize data directory?

### ISSUE THREAD

**Issue by imkane** [PascalCoinDev/PascalCoin#58]
Is there a command-line parameter to set a different data directory in Windows?

Thanks!

**Comment by SkybuckFlying** [comment]
Allowing the user to change the data directory would allow users to test PascalCoin better.

"No Database"-test-case becomes then possible for testing.

I believe this could be an important feature to have. For example to test new "checking pointing" feature to see if it allows works correctly when no database is present yet.

A way to change this in the GUI would be nice. However a config parameter/apps param in a config file would also suffice for now. It could be used to "override" default behaviour.

For example

"CustomDataFolder" could be set in config... if it's not empty... it overrides the current default user data folder location.

**Comment by Exlord** [comment]
I using a SSD as my C drive and its filling up ... I need to move the Data Directory to some where else?? Any option to to that? maybe on environment variable ?

**Comment by SkybuckFlying** [comment]
You could change the source code a little bit and re-compile with Delphi.

The following function dictates where the data folder is located:

class function TFolderHelper.GetAppDataFolder: string;

This function is in file: ..\PascalCoin\src\libraries\pascalcoin\UFolderHelper.pas

Try add this line of text below result to overwrite the previous result:

  Result := 'X:\Applications\PascalCoin\DataFolder';

Where X is the drive you want to store it on, and the rest is the folder you want to store it in.

Bye for now,
  Skybuck.

**Comment by SkybuckFlying** [comment]
Another solution is to completely move the 'appdata' folder to another drive, this would involve changing windows settings:

Windows 7:
https://www.windows-commandline.com/change-application-data-location/

Maybe windows 10 needs user folder to moved completely not sure:
https://www.tenforums.com/tutorials/1964-move-users-folder-location-windows-10-a.html

**Comment by Exlord** [comment]
> 
> 
> Another solution is to completely move the 'appdata' folder to another drive, this would involve changing windows settings:
> 
> Windows 7:
> https://www.windows-commandline.com/change-application-data-location/
> 
> Maybe windows 10 needs user folder to moved completely not sure:
> https://www.tenforums.com/tutorials/1964-move-users-folder-location-windows-10-a.html

But the article says its only recommended on fresh installs and not on a existing windows installation , bummer ... not going to risk it ... not worth it ...

**Comment by PascalCoinDev** [comment]
Done on daemon
