### ISSUE TITLE
Build for linux fails on Ubuntu Xenial x86_64

### ISSUE THREAD

**Issue by typoworx-de** [PascalCoinDev/PascalCoin#72]
Using git-source branch 2.1.3. Also tried using updated Synapse-Version by installing into Synapse and replacing existing lib/ folder with the one from sources/libs. No success.

$> fpc -FuUnits/PascalCoin/ -FuSynapse/lib/ -FuUnits/Utils/ pascalcoin_daemon.pp
> Target OS: Linux for x86-64
> Compiling pascalcoin_daemon.pp
> pascalcoin_daemon.pp(5,2) Warning: APPTYPE is not supported by the target OS
> pascalcoin_daemon.pp(12,12) Fatal: Can't find unit daemonapp used by pascalcoin_daemon

**Comment by PascalCoinDev** [comment]
Solved on 2.1.5 
Just need to delete {$apptype gui} on pascalcoin_daemon.pp file
