### ISSUE TITLE
Pascal Coin Wallet Error

### ISSUE THREAD

**Issue by xsparshx** [PascalCoinDev/PascalCoin#73]
The wallet was working fine but today when I open it, it display this error message I restarted and still it gives me this error.
" An error occurred during initialization. Application cannot continue:
Cannot open your wallet... Perhaps another instance of Pascal coin is active!
Invalid TWalletKeysExt steam
Application will close... " 

EDIT: I uninstall and reinstalled it but still the same.
I have 1 account in the wallet what should I do ?

![sss](https://user-images.githubusercontent.com/4012697/35737108-65c58a80-0850-11e8-9008-1b654fbbf668.png)

**Comment by ghost** [comment]
Delete all files and folders in AppData folder EXCEPT WALLETKEYS.DAT

**Comment by xsparshx** [comment]
In here right ? 
C:\Users\Username\AppData\Roaming\PascalCoin 
I tried but it didn't work , When I move WalletKeys.dat to other folder it worked but all my account and keys are gone... Luckily I exported my private keys before and imported it back to wallet....
But this is a big bug in the wallet what if I didn't back it up before ?
Not sure why but WalletKeys.dat got corrupted .
Please take a look and fix this bug..
Thanks for your help

**Comment by PascalCoinDev** [comment]
The message says that "another instance is active", that means that your system is running the same App twice. That's not allowed.
Simply close other app or restart system.
