### ISSUE TITLE
Compiling with lazarus and running the daemon on windows causes a crash.

### ISSUE THREAD

**Issue by EDToaster** [PascalCoinDev/PascalCoin#75]
![image](https://user-images.githubusercontent.com/7676229/36287813-35a02880-1285-11e8-8d95-460012e8f5ea.png)
![image](https://user-images.githubusercontent.com/7676229/36287817-39ce6ade-1285-11e8-9d93-87d55a54c9cd.png)
This is part of the same crash, seems to crash whenever TPCCriticalSection is referenced.

**Comment by PascalCoinDev** [comment]
Fixed on release 5.4
