### ISSUE TITLE
PoolJobs modifyed by invalid miner submit

### ISSUE THREAD

**Issue by KunNw0n** [PascalCoinDev/PascalCoin#76]
Updating Job properties in Pool List before all the checks for validity of solution submitted leads to incorrect jobs to be senе to the miner after this submission failed with proper error.
Look at [UPoolMining.pas#L820](https://github.com/PascalCoin/PascalCoin/commit/25dff89b6c600d56c117af25519dd4046b2ccafc#diff-b7250de22372e07215646ac17e7d76dbR820)
```
    l := FPoolJobs.LockList;
    Try
      i := l.Count-1;
      while (i>=0) And (Not Assigned(nbOperations)) do begin
        P := l[i];
        P^.OperationsComp.BlockPayload := _payload;
        // Best practices: Only will accept a solution if timestamp >= sent timestamp for this job (1.5.3)
        If (P^.SentMinTimestamp<=_timestamp) then begin
          P^.OperationsComp.timestamp := _timestamp;
          P^.OperationsComp.nonce := _nOnce;
          _targetPoW := FNodeNotifyEvents.Node.Bank.SafeBox.GetActualTargetHash(P^.OperationsComp.OperationBlock.protocol_version=CT_PROTOCOL_2);
if (P^.OperationsComp.OperationBlock.proof_of_work<=_targetPoW) then begin
```
In case of any of the `if`s failed - the  `_payload` value received remains in the `OperationsComp.BlockPayload` and will be included in the next response to the `miner-notify` request from the miner.

**Comment by PascalCoinDev** [comment]
I've rolled back this commit

**Comment by qualialibre** [comment]
This issue is not closed. I can get it after roughly 350 block.
I tried to mine at 20 GHz on testnet and get it every time after 1 hours (almost to the minute!)

**Comment by ghost** [comment]
qualialibre, please stop mining such a high hashrate on testnet. It’s meant for testing and now the difficulty is so high, no one else can find a block.

**Comment by qualialibre** [comment]
I know, I was trying to make a point to the other person who was mining at 15GHs and not stopping...
I will stop but it wont change a thing, the other person does not seems to understand this is a testnet !
ps: I will lower the diff, back to normal also, once the other person stops. Dont worry.
