### ISSUE TITLE
Porting to Modern Pascal and DXSock Suite.

### ISSUE THREAD

**Issue by 3FLLC** [PascalCoinDev/PascalCoin#78]
@PascalCoin  and @HermanSchoenfeld,

I am porting the code to support Modern Pascal (MPC), along with my socket suite DXSock - MPC is a mix of TP and FPC works on all the same platforms 32bit/64bit. However, I plan on adding the mining feature to MPC's CodeRunner (concept like node.js) - why not have the server doing something when not serving scripts ;-)

Plus, MPC has a built-in profiler - so I will share back any findings...
Regards,
Ozz

**Comment by HermanSchoenfeld** [comment]
Please note Development branch is Lazarus only.

**Comment by 3FLLC** [comment]
I know, what a shame. When I finish the port, it will work, Daemon, Service and support GUI, RUI and Console.

**Comment by tomasbrod** [comment]
Thank you for mentioning Modern Pascal (MPC)! I did not know about it, and I am a pascal fan. Too bad it is closed source.

**Comment by PascalCoinDev** [comment]
Current develpment (core and classic-gui) is Delphi last version compatible and also FreePascal/Lazarus last version compatible
