### ISSUE TITLE
Cannot compile miner

### ISSUE THREAD

**Issue by kwccoin** [PascalCoinDev/PascalCoin#80]
Got a few warning then a error message when compile miner:

PascalCoinMiner.pp(381,34) Error: Incompatible types: got "<procedure variable type of procedure(TLogType;TDateTime;LongWord;const AnsiString;const AnsiString) of object;Register>" expected "<procedure variable type of procedure(TLogType;TDateTime;QWord;const AnsiString;const AnsiString) of object;Register>"

Not sure how to proceed.

Compiles messages details:

[first-compile-error-message.txt](https://github.com/PascalCoin/PascalCoin/files/1780812/first-compile-error-message.txt)

Other issues bypassed:

1. Cannot find libey64d.dll not even the x64 got it; use the one comes with the Wallet
    (https://indy.fulgan.com/SSL/ even x64 is 32 dll)

2. The Synapse source tree is not exactly as described; use the source here

Just to mention deamon and wallet compile ok

**Comment by iso4free** [comment]
Also cannot compile miner for linux - got errors with DelphiCL.pas:
```
DelphiCL.pas(2199,37) Error: Incompatible types: got "Pointer" expected "LongWord"
DelphiCL.pas(2201,17) Error: Identifier not found "glXGetCurrentDisplay"
DelphiCL.pas(2576,3) Error: Identifier not found "ZeroMemory"
DelphiCL.pas(2615,3) Error: Identifier not found "ZeroMemory"
```
Using Lazarus 1.8.2/FPC 3.0.4 on Linux Mint 18.3 x64

Trying to compile for Win7 x64 got the same errors like in first post by kwwcoin.

**Comment by HermanSchoenfeld** [comment]
Try development branch.

Regards,
Herman Schoenfeld	M  +61 437 553 144
AU	T  +61 7 3195 3224	F  +61 7 3188 6009
US	T  +1 (562) 661 8263	F  +1 (562) 661 8263
2/2902 Logan Rd, Underwood QLD 4119


 <http://www.sphere10.com/>
 <http://www.sphere10.com/>

**Comment by iso4free** [comment]
From development branch everythink is ok, thanks for help.

**Comment by kwccoin** [comment]
It is ok.  But can we have an example that will work.  Just one pool example I can guess it.  Thanks.

(Or start the daemon, wallet, etc. for testing the the miner.  I am not using that but use Dual Mining.  But want to know more.  Hence, like to do testing.)

**Comment by PascalCoinDev** [comment]
Please note that miner is not tested/compiled in Linux. There is no current development to make it available on Linux
