### ISSUE TITLE
Couldn't find SameStr

### ISSUE THREAD

**Issue by bitsnaps** [PascalCoinDev/PascalCoin#83]
Hi, I'm just trying to recompile the project with Lazarus, everything seems fine except unkown function `SameStr`, so I created what seems to be the same function like so:
```
function SameStr(S1: string; S2: string): Boolean;
begin
  Result := CompareStr(S1, S2) = 0;
end;
```
I could recompile & rebuild everything successfully on Win7 64bit, the only missing piece the dll `libeay64.dll` so I copied it from the installation package, now I'm getting this error while launching the wallet:

```
Error loading OpenSSL library function "HMAC_CTX_copy" error: "The specified procedure was not found.
". Are you sure that using OpenSSL good version?
```

If this message is related to the version of OpenSSL, how do i know the exact version used in the source?

**Comment by PascalCoinDev** [comment]
As explained in https://github.com/PascalCoin/PascalCoin/wiki/Compile-instructions we're using openssl-1.1.0b

You can download Windows DLL from https://indy.fulgan.com/SSL/
