### ISSUE TITLE
[JSON-RPC getpendings] Introduce paging

### ISSUE THREAD

**Issue by Techworker** [PascalCoinDev/PascalCoin#85]
The `getpendings` JSON RPC call returns all pending operations. 

With blocks like 195718 where 10000 operations were pending it might be a good idea to adjust the procedure to accept a `start` and `max` parameter as with https://github.com/PascalCoin/PascalCoin/wiki/JSON-RPC-API#getblockoperations

**Comment by PascalCoinDev** [comment]
Added. Thanks  (also added "getpendingscount"
https://github.com/PascalCoin/PascalCoin/commit/3346db7a22b9bcb13cd83db7a18082d3eb000094

**Comment by Techworker** [comment]
Thanks for that!

Wouldn't it make sense to set the `max` default value to `0` (all pendings) for now in the getpendings method? Otherwise it's a BC - that can be changed again for V3
