### ISSUE TITLE
[TESTNET V3.1][JSON-RPC] Operation object with optype 4 (list)

### ISSUE THREAD

**Issue by Techworker** [PascalCoinDev/PascalCoin#87]
The operation object for an optype = 4 (list account for sale) does not contain any information about the sales price of an account as well as the seller account. Actually these values are available, but only in the `optxt` field of the object.

One might argue, that you can find out the price and the seller by parsing the `optxt` field value using a regular expression, but this should not be the preferred method.

`/List account (\d+\-\d+) for sale price (\b[\.,\d][^\s]*\b) PASC pay to (\d+\-\d+)/g`
 
Another workaround would be to check for any `optype` = 6 operation after the list operation to see if one bought the account and for what amount, but the price is not restricted to the list price - so it's not reliable. 

If there is no optype = 6 operation, then we can check the Account price - thats the only way it would work.

If an account is delisted, we will loose this information forever. (well, not forever - the optxt is still there..)

So my suggestion is to add these values to the operation object in case it's a list operation.

**Comment by PascalCoinDev** [comment]
Thanks.
Solved on commit
https://github.com/PascalCoin/PascalCoin/commit/365b58f09add903630af61502af79b0fc6c88453
