### ISSUE TITLE
can not save the block data into database?

### ISSUE THREAD

**Issue by wanyuehan** [PascalCoinDev/PascalCoin#9]
![1](https://cloud.githubusercontent.com/assets/10355654/18603379/7292070a-7ca3-11e6-98ca-2ab7aaf4f5b8.jpg)

block data stop to increase.
If i‘m wrong,please tell me how to correct it. Thanks, I'm a pascal's fans,but i use c++builder.

**Comment by wanyuehan** [comment]
Fork?

**Comment by PascalCoinDev** [comment]
Consider uninstall (prior, save your wallet keys) and install again... (for possible corrupted database)

Or wait few hours.

**Comment by wanyuehan** [comment]
nop,still #11999.

**Comment by wyh136** [comment]
18/09/2016 16:05:42.842 TID:00000A08 [Info] <TNetServerClient> Distinct operation block found! My:Block:11999 Timestamp:1473995021 Reward:1000000 Fee:0 PoW:0000000014D829193B1A7946254696847B86EF0F7ADFE7A532A382E500CAC092 remote:Block:12000 Timestamp:1473995264 Reward:1000000 Fee:0 PoW:000000000BFEB88E490BF90CE4EC35CBC977720549D2F9A0C32DB0EC511A879D Errors: Invalid target found:22FA61CA actual:22FA61CE
18/09/2016 16:05:42.842 TID:00000A08 [Error] <TNetServerClient> ReceivedGetOperations an unexpected operationblock: Block:12001 Timestamp:1473995429 Reward:1000000 Fee:0 PoW:00000000212AA52D5C7B0A6305281598C32D684EAB5D5C22AB979E9FAC959539
18/09/2016 16:05:43.592 TID:000008FC [Error] <TPCOperationsComp> Invalid new block 12000: Invalid target found:22FA61CA actual:22FA61CE
18/09/2016 16:05:43.592 TID:000008FC [Info] <TNetServerClient> Distinct operation block found! My:Block:11999 Timestamp:1473995021 Reward:1000000 Fee:0 PoW:0000000014D829193B1A7946254696847B86EF0F7ADFE7A532A382E500CAC092 remote:Block:12000 Timestamp:1473995264 Reward:1000000 Fee:0 PoW:000000000BFEB88E490BF90CE4EC35CBC977720549D2F9A0C32DB0EC511A879D Errors: Invalid target found:22FA61CA actual:22FA61CE
18/09/2016 16:05:43.592 TID:000008FC [Error] <TNetServerClient> ReceivedGetOperations an unexpected operationblock: Block:12001 Timestamp:1473995429 Reward:1000000 Fee:0 PoW:00000000212AA52D5C7B0A6305281598C32D684EAB5D5C22AB979E9FAC959539
18/09/2016 16:05:44.420 TID:00000940 [Error] <TPCOperationsComp> Invalid new block 12000: Invalid target found:22FA61CA actual:22FA61CE
18/09/2016 16:05:44.420 TID:00000940 [Info] <TNetServerClient> Distinct operation block found! My:Block:11999 Timestamp:1473995021 Reward:1000000 Fee:0 PoW:0000000014D829193B1A7946254696847B86EF0F7ADFE7A532A382E500CAC092 remote:Block:12000 Timestamp:1473995264 Reward:1000000 Fee:0 PoW:000000000BFEB88E490BF90CE4EC35CBC977720549D2F9A0C32DB0EC511A879D Errors: Invalid target found:22FA61CA actual:22FA61CE
18/09/2016 16:05:44.420 TID:00000940 [Error] <TNetServerClient> ReceivedGetOperations an unexpected operationblock: Block:12001 Timestamp:1473995429 Reward:1000000 Fee:0 PoW:00000000212AA52D5C7B0A6305281598C32D684EAB5D5C22AB979E9FAC959539
18/09/2016 16:05:47.264 TID:00000530 [Error] <TPCOperationsComp> Invalid new block 12000: Invalid target found:22FA61CA actual:22FA61CE
18/09/2016 16:05:47.264 TID:00000530 [Info] <TNetServerClient> Distinct operation block found! My:Block:11999 Timestamp:1473995021 Reward:1000000 Fee:0 PoW:0000000014D829193B1A7946254696847B86EF0F7ADFE7A532A382E500CAC092 remote:Block:12000 Timestamp:1473995264 Reward:1000000 Fee:0 PoW:000000000BFEB88E490BF90CE4EC35CBC977720549D2F9A0C32DB0EC511A879D Errors: Invalid target found:22FA61CA actual:22FA61CE
18/09/2016 16:05:47.264 TID:00000530 [Error] <TNetServerClient> ReceivedGetOperations an unexpected operationblock: Block:12001 Timestamp:1473995429 Reward:1000000 Fee:0 PoW:00000000212AA52D5C7B0A6305281598C32D684EAB5D5C22AB979E9FAC959539
18/09/2016 16:05:49.748 TID:00000920 [Error] <TPCOperationsComp> Invalid new block 12000: Invalid target found:22FA61CA actual:22FA61CE
18/09/2016 16:05:49.748 TID:00000920 [Info] <TNetServerClient> Distinct operation block found! My:Block:11999 Timestamp:1473995021 Reward:1000000 Fee:0 PoW:0000000014D829193B1A7946254696847B86EF0F7ADFE7A532A382E500CAC092 remote:Block:12000 Timestamp:1473995264 Reward:1000000 Fee:0 PoW:000000000BFEB88E490BF90CE4EC35CBC977720549D2F9A0C32DB0EC511A879D Errors: Invalid target found:22FA61CA actual:22FA61CE
18/09/2016 16:05:49.748 TID:00000920 [Error] <TNetServerClient> ReceivedGetOperations an unexpected operationblock: Block:12001 Timestamp:1473995429 Reward:1000000 Fee:0 PoW:00000000212AA52D5C7B0A6305281598C32D684EAB5D5C22AB979E9FAC959539

**Comment by PascalCoinDev** [comment]
Build 1.0.6 corrects this

**Comment by privatenode** [comment]
lol, still didn't fix, what a joke coin.
