### ISSUE TITLE
App glitching

### ISSUE THREAD

**Issue by apolousm** [PascalCoinDev/PascalCoin#91]
The new wallet stops responding (hangs) while it does some sort of cell scan: you can see the app scanning the accounts (from left to right), and it hangs for a moment.

**Comment by HermanSchoenfeld** [comment]
New wallet as in latest release or 'master' build?

**Comment by apolousm** [comment]
I downloaded this one: PascalCoinWallet_64b_B3.0.1.exe
Is that the master build?

**Comment by PascalCoinDev** [comment]
Yes. This is the current release
