### ISSUE TITLE
Op 1/1:Invalid sign

### ISSUE THREAD

**Issue by tebgeni** [PascalCoinDev/PascalCoin#93]
Hello, I have a problem with my wallet. When I'm trying to make a transaction, after confirmation I have this message and I don;t know what I am doing wrong. Please help me.

![pascal_error](https://user-images.githubusercontent.com/39098089/39772054-72ce1ed8-52f4-11e8-935a-0153f7eb876a.png)

**Comment by PascalCoinDev** [comment]
It's solved downloading and installing Wallet again

Download last valid from https://github.com/PascalCoin/PascalCoin/releases

Thanks
